### Getting started
GET localhost:3000


### Create a new name
POST localhost:3000/name
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe"
}


### Get all names
GET localhost:3000/names